[workspace]
# members = ["protocol"]

[package]
name = "web-socket"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/nurmohammed840/websocket.rs"
authors = ["Nur <nurmohammed840@gmail.com>"]
keywords = ["ws", "websocket"]
description = "WebSocket implementation for both client and server"


[dependencies]
tokio = { version = "1.21", features = ["io-util", "net"] }
sha-1 = "0.10"
base64 = "0.13"
fastrand = "1.8"

[dev-dependencies]
tokio = { version = "1.21", features = ["rt"] }
