[package]
name = "web-socket"
version = "0.4.0"
edition = "2021"

license = "Apache-2.0"
keywords = ["ws", "websocket"]
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/websocket.rs"
description = "WebSocket implementation for both client and server"

exclude = ["/examples", "/autobahn", "/tests",  ".*"]

[features]
default = ["server", "tls", "client"]
server = []
tls = ["dep:tokio-rustls", "dep:webpki-roots"]
client = ["http", "tokio/net"]
http = ["dep:base64", "dep:sha-1"]

[dependencies]
tokio = { version = "1", default-features = false, features = ["io-util"] }

# feature: tls
tokio-rustls = { version = "0.23", default-features = false, optional = true }
webpki-roots = { version = "0.22", optional = true }

# feature: http 
base64 = { version = "0.21", optional = true }
sha-1 = { version = "0.10", optional = true }

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }