[package]
name = "web-socket"
version = "0.3.0"
edition = "2021"

license = "Apache-2.0"
keywords = ["ws", "websocket"]
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/websocket.rs"
description = "WebSocket implementation for both client and server"

[dependencies]
tokio = { version = "1", default-features = false, features = ["io-util", "net"] }
tokio-rustls = { version = "0.23", default-features = false }
webpki-roots = "0.22"

base64 = "0.21"
sha-1 = "0.10"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }